refactor: network DI 구조로 리펙터링
f-lab-edu/PurpleCoin pull request #4
Opened 2024-02-11 09:33 UTC by kang-jae-heok

### Network Refactor
네트워크쪽 DI구조로 바꿨습니다
원래 뷰모델에 있는 전역 변수로 데이터를 get set했었는데 뷰모델과 뷰컨트롤러의 결합도를 낮추려고 일단은 뷰컨트롤러의 전역 변수로 바꿨습니다.
이게 맞는 방법인지 커멘트 부탁드립니다!
에러는 일단은 print 되어있는데 추후에 코드가 좀 정리되면 얼러트를 띄우는 걸로 업데이트 예정입니다.

2024-02-11 13:03 UTC, abdul0986 commented
코드 분석 툴에서 이슈로 뽑은 것들이 많네요. 우선 수정해주세요~

2024-02-12 14:26 UTC, abdul0986 requested changes
수정 요청드립니다.

2024-02-12 14:26 UTC, abdul0986 commented on PurpleCoin/PurpleCoin/Services/Network/APIService.swift
> +    func getAllMarketCode() async throws -> [MarketCode] {
주석이 잘못된 것 같습니다. 특정 코인 정보들이 아니라 전체 마켓 코드를 가져오는 것 아닌가 싶은데요.

2024-02-12 14:26 UTC, abdul0986 commented on PurpleCoin/PurpleCoin/ViewModel/MarketViewModel.swift
> +            print("Error: \(error)")
print 구문은 제거해주세요

2024-02-12 14:26 UTC, abdul0986 commented on PurpleCoin/PurpleCoin/Services/Network/APIService.swift
> +            provider.request(.getAllMarketCode) { result in
전체 코드를 읽어와야 하는 거면 네트워크 부하가 좀 있을 듯 한데 로컬 캐싱을 하셔야 할 듯 합니다.

2024-02-12 14:26 UTC, abdul0986 commented on PurpleCoin/PurpleCoin/Services/Network/APIService.swift
>                  }
바로 위에 있는 getAllMarketCode() 함수와 패턴이 상당히 유사한데 겹치는 중복 코드를 제거할 방법을 고민해주세요

2024-02-12 14:26 UTC, abdul0986 commented on PurpleCoin/PurpleCoin/Services/Network/APIService.swift
> +    func getAllMarketCode() async throws -> [MarketCode] {
함수 명은 `getAllMarketCodes()`와 같이 복수형으로 처리되어야 합니다.

2024-02-12 14:26 UTC, abdul0986 commented on PurpleCoin/PurpleCoin/View/DetailCoin/View/DetailCoinViewController.swift
>  class DetailCoinViewController: UIViewController {
final 붙여주세요

2024-02-12 14:26 UTC, abdul0986 commented on PurpleCoin/PurpleCoin/View/DetailCoin/View/DetailCoinViewController.swift
>          }
guard 구문보다 cell 할당문이 먼저 작성되어 있는데, 순서 변경해주세요

2024-02-18 09:16 UTC, kang-jae-heok commented on PurpleCoin/PurpleCoin/Services/Network/APIService.swift
> +    func getAllMarketCode() async throws -> [MarketCode] {
바꿨습니다

2024-02-18 09:17 UTC, kang-jae-heok commented on PurpleCoin/PurpleCoin/ViewModel/MarketViewModel.swift
> +            print("Error: \(error)")
이게 에러를 안쓰면 swiftlint에 걸려서 임시로 해놨는데 일단 이렇게 해놓고 최대한 빠르게 에러에 대한 처리를 해놓겠습니다!

2024-02-18 14:35 UTC, kang-jae-heok commented on PurpleCoin/PurpleCoin/Services/Network/APIService.swift
> +            provider.request(.getAllMarketCode) { result in
networkConfig에서 userdefaults에 만료시간을 임의로 정해서 valid 체크하는 로직을 구현했습니다.

2024-02-18 14:39 UTC, kang-jae-heok commented on PurpleCoin/PurpleCoin/Services/Network/APIService.swift
>                  }
이게 에러타입을 해당 리퀘스트 스코프안에서 정의를 해주는데 이게 공통으로 뺄 수 있는 방법이 있나요?

2024-02-18 14:40 UTC, kang-jae-heok commented on PurpleCoin/PurpleCoin/View/DetailCoin/View/DetailCoinViewController.swift
>  class DetailCoinViewController: UIViewController {
붙였습니다.

2024-02-18 14:42 UTC, kang-jae-heok commented on PurpleCoin/PurpleCoin/View/DetailCoin/View/DetailCoinViewController.swift
>          }
바꿨습니다

2024-02-19 11:30 UTC, abdul0986 commented on PurpleCoin/PurpleCoin/Services/Network/APIService.swift
>                  }
제너릭은 어떤가요?

2024-02-19 11:32 UTC, abdul0986 commented
SwiftLint / SwiftLint Failing이 계속 발생하고 있는데, 한번 확인해주셔야 할 듯 싶어요

2024-02-22 10:21 UTC, merged